### ISSUE TITLE
Update to red panda ?

### ISSUE THREAD

**Issue by gedw99** [bemoore34/Redpanda-Connect-Custom-Plugins#1]
I guess this needs a reference update to red panda ?

**Comment by bemoore34** [comment]
Yes, that is correct, thanks. I have these custom inputs working with the RedPanda repos and need to update these files accordingly. I'll try to get that done soon in case anyone else is trying to make them work.

**Comment by bemoore34** [comment]
I have updated the files. Confirmed the compile and run, but didn't do much real testing. Let me know if you have any issues. Thanks.
